import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Offer from "@/components/Offer/page";
import Navbar from "@/components/Navbar/page";
import Navbar2 from "@/components/navbar2/page";
import Footer from "@/components/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pachmani Ayurveda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Offer />
          <Navbar />
          <Navbar2 />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
